const JMA_BT = "https://www.jma.go.jp/jma/jma-eng/jma-center/rsmc-hp-pub-eg/Besttracks/bst_all.zip"
const IBTRACS_WP_BT = "https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r00/access/csv/ibtracs.WP.list.v04r00.csv"

const DB = joinpath(@__DIR__, "../db")
const DB_POLY = joinpath(DB, "poly")
const JMA_DB = joinpath(DB, "jma")
const JMA_BT_DB = joinpath(JMA_DB, "bt")
const IBTRACS_DB = joinpath(DB, "ibtracs")
const IBTRACS_BT_DB = joinpath(IBTRACS_DB, "bt")
const BRN_POLY = joinpath(DB_POLY, "brn")
const CHN_POLY = joinpath(DB_POLY, "chn")
const JPN_POLY = joinpath(DB_POLY, "jpn")
const KHM_POLY = joinpath(DB_POLY, "khm")
const KOR_POLY = joinpath(DB_POLY, "kor")
const LAO_POLY = joinpath(DB_POLY, "lao")
const MMR_POLY = joinpath(DB_POLY, "mmr")
const MNG_POLY = joinpath(DB_POLY, "mng")
const MYS_POLY = joinpath(DB_POLY, "mys")
const PHL_POLY = joinpath(DB_POLY, "phl")
const PRK_POLY = joinpath(DB_POLY, "prk")
const RUS_POLY = joinpath(DB_POLY, "rus")
const THA_POLY = joinpath(DB_POLY, "tha")
const TWN_POLY = joinpath(DB_POLY, "twn")
const VNM_POLY = joinpath(DB_POLY, "vnm")
const ASIA_POLY = joinpath(@__DIR__, "../assets/asia_geo.json")

# URLs
const BRN_GEOJSON = "https://raw.githubusercontent.com/alstat/BagyoData/main/WP/BRN/brn_geo.json";
const CHN_GEOJSON = "https://raw.githubusercontent.com/alstat/BagyoData/main/WP/CHN/chn_geo.json";
const JPN_GEOJSON = "https://raw.githubusercontent.com/alstat/BagyoData/main/WP/JPN/jpn_geo.json";
const KHM_GEOJSON = "https://raw.githubusercontent.com/alstat/BagyoData/main/WP/KHM/khm_geo.json";
const KOR_GEOJSON = "https://raw.githubusercontent.com/alstat/BagyoData/main/WP/KOR/kor_geo.json";
const LAO_GEOJSON = "https://raw.githubusercontent.com/alstat/BagyoData/main/WP/LAO/lao_geo.json";
const MMR_GEOJSON = "https://raw.githubusercontent.com/alstat/BagyoData/main/WP/MMR/mmr_geo.json";
const MNG_GEOJSON = "https://raw.githubusercontent.com/alstat/BagyoData/main/WP/MNG/mng_geo.json";
const MYS_GEOJSON = "https://raw.githubusercontent.com/alstat/BagyoData/main/WP/MYS/mys_geo.json";
const PHL_GEOJSON = "https://raw.githubusercontent.com/alstat/BagyoData/main/WP/PHL/phl_geo.json";
const PRK_GEOJSON = "https://raw.githubusercontent.com/alstat/BagyoData/main/WP/PRK/prk_geo.json";
const RUS_GEOJSON = "https://raw.githubusercontent.com/alstat/BagyoData/main/WP/RUS/rus_geo.json";
const THA_GEOJSON = "https://raw.githubusercontent.com/alstat/BagyoData/main/WP/THA/tha_geo.json";
const TWN_GEOJSON = "https://raw.githubusercontent.com/alstat/BagyoData/main/WP/TWN/twn_geo.json";
const VNM_GEOJSON = "https://raw.githubusercontent.com/alstat/BagyoData/main/WP/VNM/vnm_geo.json";